name       : uget
version    : 2.2.3
release    : 13
source     :
    - https://liquidtelecom.dl.sourceforge.net/project/urlget/uget%20%28stable%29/2.2.3/uget-2.2.3-1.tar.gz : 11356e4242151b9014fa6209c1f0360b699b72ef8ab47dbeb81cc23be7db9049
homepage   : https://ugetdm.com/
license    : LGPL-2.1-or-later
component  : network.download
summary    : url-get download manager
description: |
    uGet is a download manager that combines lightweight resource usage with a very powerful feature set.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
setup      : |
    %configure --disable-rss-notify
build      : |
    %make
install    : |
    %make_install
