name       : uget
version    : 2.0.8
release    : 7
source     :
    - http://internode.dl.sourceforge.net/project/urlget/uget%20%28stable%29/2.0.8/uget-2.0.8.tar.gz : e5ccf61ed691d8921e2f1951b1cf8eb439b525868a0d0068932d4c478f632924
license    : GPL-3.0
component  : network.download
summary    : url-get download manager
description: |
    url-get download manager
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
