name       : uget
version    : 2.0.4
release    : 5
source     :
    - http://internode.dl.sourceforge.net/project/urlget/uget%20%28stable%29/2.0.4/uget-2.0.4.tar.gz : 25b7664e9badf39c8c621cd4f19896bb8b594e1c80c17e856c67d1273fd9dce5
license    : GPL-3.0
summary    : ulr-get download manager
description: |
    url-get download manager
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(gstreamer-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
