name       : uget
version    : 2.0.5
release    : 6
source     :
    - http://internode.dl.sourceforge.net/project/urlget/uget%20%28stable%29/2.0.5/uget-2.0.5.tar.gz : 033adbeeec3a20f2b979cabcfd014e0e7e51e47f371a7e405591f9861a431f33
license    : GPL-3.0
summary    : ulr-get download manager
description: |
    url-get download manager
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(gstreamer-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
