name       : uget
version    : 2.0.3
release    : 4
source     :
    - http://internode.dl.sourceforge.net/project/urlget/uget%20%28stable%29/2.0.3/uget-2.0.3.tar.gz : 78b4e899ce8eadc4bc6189fdb65c577757a84d0d829340c1bdf047723c90d055
license    : GPL-3.0
summary    : ulr-get download manager
description: |
    url-get download manager
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(gstreamer-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
