name       : uget
version    : 2.2.0
release    : 9
source     :
    - http://internode.dl.sourceforge.net/project/urlget/uget%20%28stable%29/2.2.0/uget-2.2.0.tar.gz : 552c325a82eed30e5e95428a3fb1ddeb41e1cf6da57eb4a2b4bb37cb44aee265
license    : GPL-3.0
component  : network.download
summary    : url-get download manager
description: |
    url-get download manager
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
setup      : |
    %configure --disable-rss-notify
build      : |
    %make
install    : |
    %make_install
