name       : uget
version    : 2.0.9
release    : 8
source     :
    - http://internode.dl.sourceforge.net/project/urlget/uget%20%28stable%29/2.0.9/uget-2.0.9.tar.gz : 5501c1d0c17e2e7b689eaaeae959d6c9c1f7855daf82086858efcb1e4d4208d6
license    : GPL-3.0
component  : network.download
summary    : url-get download manager
description: |
    url-get download manager
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
