name       : uget
version    : 2.2.2
release    : 11
source     :
    - http://internode.dl.sourceforge.net/project/urlget/uget%20%28stable%29/2.2.2/uget-2.2.2.tar.gz : 5cf7f311ef59bd02b71e0ce750dd37a0299ef15f9f6c6e7e60ffd175409abfc2
license    : GPL-3.0-or-later
component  : network.download
summary    : url-get download manager
description: |
    url-get download manager
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(libcurl)
    - pkgconfig(libnghttp2)
    - pkgconfig(libnotify)
    - pkgconfig(libssh2)
setup      : |
    %configure --disable-rss-notify
build      : |
    %make
install    : |
    %make_install
