name       : uget
version    : 2.0
release    : 1
source     :
    - http://jaist.dl.sourceforge.net/project/urlget/uget%20%28stable%29/2.0/uget-2.0.tar.gz : d857bbf1bb3ca7a9943b26a51e20a488e0750b1e2eeff713ef3fdff40320e496
license    : GPL-3.0
summary    : ulr-get download manager
description: |
    url-get download manager
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(gstreamer-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
