name       : uget
version    : 2.2.3
release    : 14
source     :
    - https://downloads.sourceforge.net/urlget/uget-2.2.3-1.tar.gz : 11356e4242151b9014fa6209c1f0360b699b72ef8ab47dbeb81cc23be7db9049
homepage   : https://ugetdm.com/
license    : LGPL-2.1-or-later
component  : network.download
summary    : url-get download manager
description: |
    uGet is a download manager that combines lightweight resource usage with a very powerful feature set.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
setup      : |
    %patch -p1 -i $pkgfiles/0001-Fix-build-with-gcc-10.patch
    %patch -p1 -i $pkgfiles/0001-Disable-RSS.patch

    # Prevent it from forcing x11
    sed -i 's/env GDK_BACKEND=x11 uget-gtk/uget-gtk/' uget-gtk.desktop

    %configure --disable-rss-notify
build      : |
    %make
install    : |
    %make_install
