name       : uget
version    : 2.0.1
release    : 2
source     :
    - http://jaist.dl.sourceforge.net/project/urlget/uget%20(stable)/2.0.1/uget-2.0.1.tar.gz : eca884d2bdb3877a2f3286f67fa7d3a3284591d4222136770dbf8a68d610ffed
license    : GPL-3.0
summary    : ulr-get download manager
description: |
    url-get download manager
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(gstreamer-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
