name       : uget
version    : 2.0.2
release    : 3
source     :
    - http://jaist.dl.sourceforge.net/project/urlget/uget%20%28stable%29/2.0.2/uget-2.0.2.tar.gz : b6c185215926dc0dcaed6681e43d92dbd65b5cf1b3cf18018eab1f2a789c021c
license    : GPL-3.0
summary    : ulr-get download manager
description: |
    url-get download manager
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(gstreamer-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
